### ISSUE TITLE
Road Safety Data

### ISSUE THREAD

**Issue by daryasy** [kipyegonline/accidentsStats#1]
Hi! I am writing you here because did not manage to find your any other contacts)
I am a student at the Prague University of Economics and Business.
Currently, I am making research on road traffic safety around the world for the Business Intelligence subject and I have faced an issue with collecting related data for Kenya. 
So, I am writing to ask for help if you have any data related to Kenya's road traffic situation in 2010-2020, including:
number of traffic accidents, 
injuries
fatalities
number of motor vehicles in use
investments spent on maintenance and road innovations
This data will be used for educational purposes only.
I would be very grateful for any help, my email sivd02@vse.cz.
Thank you in advance:)

**Comment by kipyegonline** [comment]
The stats can be found here, https://www.ntsa.go.ke/site/ ....  Kenya's
National Transport and Safety Authority official website.


***@***.*** ***@***.***> *
